version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - ./database/data:/var/lib/postgresql/data:rw
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    restart: always
    container_name: rabbitmq-broker
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  titan:
    depends_on:
      - postgres
    container_name: titan-microservice
    build:
      dockerfile: Dockerfile
      context: ./titan
    ports:
      - 8081:8081
  fenrir:
    depends_on:
      - postgres
    container_name: fenrir-microservice
    build:
      dockerfile: Dockerfile
      context: ./fenrir
    ports:
      - 8082:8082
